services:
  chatbot:
    container_name: chatbot
    image: chatbot-python:latest
    ports:
      - "${CHATBOT_PORT}:${CHATBOT_PORT}"
    networks:
      - chatbot_network

  waha_api:
    container_name: waha_api
    image: devlikeapro/waha
    ports:
      - "${WAHA_PORT}:${WAHA_PORT}"
    networks:
      - chatbot_network
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    depends_on:
      - chatbot

networks:
  chatbot_network:
    name: chatbot_network
    driver: bridge
    