name: Compare API Responses via Kafka

on:
  pull_request:

jobs:
  compare:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
      kafka:
        image: wurstmeister/kafka:2.12-2.2.1
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: pr_branch

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: main_branch

      - name: Build and run both APIs
        run: |
          cd pr_branch
          docker build -t api-pr .
          docker run -d -p 8001:8000 --name api-pr api-pr
          cd ../main_branch
          docker build -t api-main .
          docker run -d -p 8002:8000 --name api-main api-main

      - name: Install dependencies
        run: pip install confluent-kafka httpx

      - name: Run Kafka test comparator
        run: python main_branch/compare/kafka_comparator.py
        env:
          KAFKA_BROKER: localhost:9092
          API_MAIN_URL: http://localhost:8001  # ajuste a porta se necessário
          API_BRANCH_URL: http://localhost:8002  # ajuste a porta se