name: Compare API Responses via Kafka

on:
  pull_request:

jobs:
  compare:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: pr_branch

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: main_branch

      - name: Build and run both APIs
        run: |
          cd pr_branch
          docker build -t api-pr .
          docker run -d -p 8001:8000 --name api-pr api-pr
          cd ../main_branch
          docker build -t api-main .
          docker run -d -p 8002:8000 --name api-main api-main

      - name: Install dependencies
        run: pip install confluent-kafka httpx 

      - name: Run Kafka test comparator
        run: python pr_branch/compare/kafka_comparator.py
        env:
          KAFKA_BROKER: kafka:9092
          API_MAIN_URL: http://api-main:8001  # ajuste a porta se necessário
          API_BRANCH_URL: http://api-pr:8002  # ajuste a porta se